SensorViewConfiguration:
  version:
    - is_set
  sensor_id:
    - is_set
  mounting_position:
    - is_set
  mounting_position_rmse:
    - is_set
  field_of_view_horizontal:
    - is_set
  field_of_view_vertical:
    - is_set
  range:
    - is_minimum: 0
  update_cycle_time:
    - is_set
  update_cycle_offset:
    - is_set
  simulation_start_time:
    - is_set
  
GenericSensorViewConfiguration:
  sensor_id:
    - is_set
  mounting_position:
    - is_set
  mounting_position_rmse:
    - is_set
  field_of_view_horizontal:
    - is_set
  field_of_view_vertical:
    - is_set

RadarSensorViewConfiguration:
  sensor_id:
    - is_set
  mounting_position:
    - is_set
  mounting_position_rmse:
    - is_set
  field_of_view_horizontal:
    - is_set
  field_of_view_vertical:
    - is_set
  number_of_rays_horizontal:
    - is_minimum: 1
  number_of_rays_vertical:
    - is_minimum: 1
  max_number_of_interactions:
    - is_minimum: 1
  emitter_frequency:
    - is_minimum: 0
  tx_antenna_diagram:
    - is_set
  rx_antenna_diagram:
    - is_set
  AntennaDiagramEntry:
    horizontal_angle:
      - is_set
    vertical_angle:
      - is_set
    response:
      - is_set

LidarSensorViewConfiguration:
  sensor_id:
    - is_set
  mounting_position:
    - is_set
  mounting_position_rmse:
    - is_set
  field_of_view_horizontal:
    - is_set
  field_of_view_vertical:
    - is_set
  number_of_rays_horizontal:
    - is_minimum: 1
  number_of_rays_vertical:
    - is_minimum: 1
  max_number_of_interactions:
    - is_minimum: 1
  emitter_frequency:
    - is_minimum: 0
  num_of_pixels:
    - is_minimum: 1
  
CameraSensorViewConfiguration:
  sensor_id:
    - is_set
  mounting_position:
    - is_set
  mounting_position_rmse:
    - is_set
  field_of_view_horizontal:
    - is_set
  field_of_view_vertical:
    - is_set
  number_of_pixels_horizontal:
    - is_minimum: 1
  number_of_pixels_vertical:
    - is_minimum: 1
  channel_format:
    - is_minimum: 1


UltrasonicSensorViewConfiguration:
  sensor_id:
    - is_set
  mounting_position:
    - is_set
  mounting_position_rmse:
    - is_set
  field_of_view_horizontal:
    - is_set
  field_of_view_vertical:
    - is_set